pidev_evenement:
    resource: "@PIDEVEvenementBundle/Resources/config/routing.yml"
    prefix:   /

pidev_produit:
    resource: "@PIDEVProduitBundle/Resources/config/routing.yml"
    prefix:   /

pidev_prestation:
    resource: "@PIDEVPrestationBundle/Resources/config/routing.yml"
    prefix:   /

pidev_user:
    resource: "@PIDEVUserBundle/Resources/config/routing.yml"
    prefix:   /

pidev_template:
    resource: "@PIDEVTemplateBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"