pidev_template_homepage:
    path:     /
    defaults: { _controller: PIDEVTemplateBundle:Default:index }
layout:
    path:     /layout
    defaults: { _controller: PIDEVTemplateBundle:Default:Dashboard }
Front:
    path:     /front
    defaults: { _controller: PIDEVTemplateBundle:Default:Front }
